###
GET http://localhost:8000/be/category

###
GET http://localhost:8000/be/category/1


###
POST http://localhost:8000/be/category
Content-Type: application/json

{
    "categoryName": "Eyepatch",
    "link": "/eyepatch"
}

###
PUT http://localhost:8000/be/category/2
Content-Type: application/json

{
      "categoryName": "t-shirt"   
}
###
DELETE http://localhost:8000/be/category/2